In [8]:
import pandas as pd
from pathlib import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [9]:
# Read salary data
file_path = Path("All_data_cleaned.csv")
crime = pd.read_csv(file_path)

# Display sample data
crime.head()

,Year,City,Population 25 years and over - Less than 9th grade,Percent Population 25 years and over - Less than 9th grade,Population 25 years and over - 9th to12th (No Diploma),Percent Population 25 years and over - 9th to12th (No Diploma),Population 25 years and over - High School Graduate (and equivalent),Percent Population 25 years and over - High School Graduate (and equivalent),"Population 25 years and over - Some college, no degree","Percent Population 25 years and over - Some college, no degree",...,75 to 84 years,Percent 75 to 84 years,85 years and over,Percent 85 years and over,Violent Crimes Sum,% All Families,House Price Mean,Total,Total Occupied,Renter occupied
0,2015,Alameda,2089,3.6,2089,3.6,7242,12.3,11010,18.7,...,"3,599",4.60%,"1,541",2.00%,148.0,5.2,789464.7,"30,710","13,544","17,166"
1,2015,Alhambra,5402,8.3,4923,7.6,18760,28.8,9435,14.5,...,"3,237",3.80%,"2,210",2.60%,168.0,11.8,524186.5,"29,362","12,184","17,178"
2,2015,Anaheim,32506,14.4,25762,11.4,53477,23.6,47633,21.1,...,"10,167",2.90%,"5,608",1.60%,1271.0,11.8,479128.8,"99,991","43,468","56,523"
3,2015,Bakersfield,23326,10.6,22434,10.2,63568,28.8,46592,21.1,...,"9,168",2.50%,"3,276",0.90%,1810.0,14.3,214306.0,"114,383","66,085","48,298"
4,2015,Baldwin Park,11082,22.1,6156,12.3,15636,31.1,7172,14.3,...,"2,120",2.80%,933,1.20%,299.0,14.4,343992.4,"18,541","10,092","8,449"

In [10]:
columns_to_convert = [
    'Total population', 'Under 5 years', 'Percent Under 5 years', 
    '5 to 9 years', 'Percent 5 to 9 years', '10 to 14 years', 
    'Percent 10 to 14 years', '15 to 19 years', 'Percent 15 to 19 years', 
    '20 to 24 years', 'Percent 20 to 24 years', '25 to 34 years', 
    'Percent 25 to 34 years', '35 to 44 years', 'Percent 35 to 44 years', 
    '45 to 54 years', 'Percent 45 to 54 years', '55 to 59 years', 
    'Percent 55 to 59 years', '60 to 64 years', 'Percent 60 to 64 years', 
    '65 to 74 years', 'Percent 65 to 74 years', '75 to 84 years', 
    'Percent 75 to 84 years', '85 years and over', 'Percent 85 years and over', 'Total', 'Total Occupied', 'Renter occupied'
]

for column in columns_to_convert:
    crime[column] = crime[column].str.replace(',|%', '', regex=True) .astype(float)

In [11]:
# Define features set
X = crime.copy()
X.drop(columns=["Violent Crimes Sum", "City"], axis=1, inplace=True)
X.head()

,Year,Population 25 years and over - Less than 9th grade,Percent Population 25 years and over - Less than 9th grade,Population 25 years and over - 9th to12th (No Diploma),Percent Population 25 years and over - 9th to12th (No Diploma),Population 25 years and over - High School Graduate (and equivalent),Percent Population 25 years and over - High School Graduate (and equivalent),"Population 25 years and over - Some college, no degree","Percent Population 25 years and over - Some college, no degree",Population 25 years and over - Associate's degree,...,Percent 65 to 74 years,75 to 84 years,Percent 75 to 84 years,85 years and over,Percent 85 years and over,% All Families,House Price Mean,Total,Total Occupied,Renter occupied
0,2015,2089,3.6,2089,3.6,7242,12.3,11010,18.7,4306,...,8.3,3599.0,4.6,1541.0,2.0,5.2,789464.7,30710.0,13544.0,17166.0
1,2015,5402,8.3,4923,7.6,18760,28.8,9435,14.5,3932,...,9.0,3237.0,3.8,2210.0,2.6,11.8,524186.5,29362.0,12184.0,17178.0
2,2015,32506,14.4,25762,11.4,53477,23.6,47633,21.1,14397,...,5.8,10167.0,2.9,5608.0,1.6,11.8,479128.8,99991.0,43468.0,56523.0
3,2015,23326,10.6,22434,10.2,63568,28.8,46592,21.1,17529,...,6.1,9168.0,2.5,3276.0,0.9,14.3,214306.0,114383.0,66085.0,48298.0
4,2015,11082,22.1,6156,12.3,15636,31.1,7172,14.3,3162,...,9.0,2120.0,2.8,933.0,1.2,14.4,343992.4,18541.0,10092.0,8449.0

In [12]:
y = crime["Violent Crimes Sum"].values.reshape(-1, 1)
y[:5]

array([[ 148.],
       [ 168.],
       [1271.],
       [1810.],
       [ 299.]])

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [14]:
# Create the StandardScaler instance
scaler = StandardScaler()

In [15]:
# Fit the Standard Scaler with the training data
X_scaler = scaler.fit(X_train)

In [16]:
# Scale the training data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [23]:
# Create the random forest classifier instance
rf_model = RandomForestClassifier(n_estimators=10000)

In [24]:
# Fit the model and use .ravel()on the "y_train" data. 
rf_model = rf_model.fit(X_train_scaled, y_train.ravel())

In [25]:
# Making predictions using the testing data
predictions = rf_model.predict(X_test_scaled)

In [26]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)

labels = [f"Class {i}" for i in range(len(cm))]

cm_df = pd.DataFrame(cm, index=labels, columns=labels)

# Calculating the accuracy score
acc_score = accuracy_score(y_test, predictions)

In [27]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

,Class 0,Class 1,Class 2,Class 3,Class 4,Class 5,Class 6,Class 7,Class 8,Class 9,...,Class 226,Class 227,Class 228,Class 229,Class 230,Class 231,Class 232,Class 233,Class 234,Class 235
Class 0,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Class 1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Class 2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Class 3,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Class 4,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Class 231,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
Class 232,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Class 233,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Class 234,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Class 235,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

Accuracy Score : 0.0
Classification Report
              precision    recall  f1-score   support

        39.0       0.00      0.00      0.00       1.0
        41.0       0.00      0.00      0.00       1.0
        43.0       0.00      0.00      0.00       0.0
        49.0       0.00      0.00      0.00       1.0
        52.0       0.00      0.00      0.00       1.0
        65.0       0.00      0.00      0.00       0.0
        68.0       0.00      0.00      0.00       1.0
        70.0       0.00      0.00      0.00       1.0
        72.0       0.00      0.00      0.00       0.0
        82.0       0.00      0.00      0.00       0.0
        85.0       0.00      0.00      0.00       0.0
        86.0       0.00      0.00      0.00       1.0
       100.0       0.00      0.00      0.00       1.0
       102.0       0.00      0.00      0.00       1.0
       105.0       0.00      0.00      0.00       1.0
       109.0       0.00      0.00      0.00       0.0
       110.0       0.00      0.00      0.00       1.0
       112.0       0.00      0.00      0.00       1.0
       120.0       0.00      0.00      0.00       0.0
       123.0       0.00      0.00      0.00       1.0
       132.0       0.00      0.00      0.00       1.0
       135.0       0.00      0.00      0.00       0.0
       139.0       0.00      0.00      0.00       1.0
       144.0       0.00      0.00      0.00       0.0
       145.0       0.00      0.00      0.00       1.0
       146.0       0.00      0.00      0.00       0.0
       148.0       0.00      0.00      0.00       0.0
       149.0       0.00      0.00      0.00       1.0
       151.0       0.00      0.00      0.00       1.0
       158.0       0.00      0.00      0.00       0.0
       159.0       0.00      0.00      0.00       2.0
       160.0       0.00      0.00      0.00       0.0
       161.0       0.00      0.00      0.00       0.0
       164.0       0.00      0.00      0.00       2.0
       165.0       0.00      0.00      0.00       0.0
       166.0       0.00      0.00      0.00       1.0
       169.0       0.00      0.00      0.00       1.0
       172.0       0.00      0.00      0.00       0.0
       173.0       0.00      0.00      0.00       1.0
       174.0       0.00      0.00      0.00       1.0
       177.0       0.00      0.00      0.00       1.0
       180.0       0.00      0.00      0.00       1.0
       184.0       0.00      0.00      0.00       1.0
       185.0       0.00      0.00      0.00       0.0
       188.0       0.00      0.00      0.00       1.0
       189.0       0.00      0.00      0.00       0.0
       190.0       0.00      0.00      0.00       0.0
       192.0       0.00      0.00      0.00       1.0
       193.0       0.00      0.00      0.00       2.0
       197.0       0.00      0.00      0.00       0.0
       199.0       0.00      0.00      0.00       0.0
       202.0       0.00      0.00      0.00       1.0
       208.0       0.00      0.00      0.00       1.0
       209.0       0.00      0.00      0.00       1.0
       210.0       0.00      0.00      0.00       1.0
       212.0       0.00      0.00      0.00       1.0
       214.0       0.00      0.00      0.00       0.0
       218.0       0.00      0.00      0.00       0.0
       222.0       0.00      0.00      0.00       0.0
       223.0       0.00      0.00      0.00       2.0
       225.0       0.00      0.00      0.00       2.0
       227.0       0.00      0.00      0.00       0.0
       228.0       0.00      0.00      0.00       1.0
       229.0       0.00      0.00      0.00       0.0
       231.0       0.00      0.00      0.00       1.0
       232.0       0.00      0.00      0.00       0.0
       233.0       0.00      0.00      0.00       1.0
       234.0       0.00      0.00      0.00       0.0
       237.0       0.00      0.00      0.00       1.0
       242.0       0.00      0.00      0.00       2.0
       243.0       0.00      0.00      0.00       0.0
       244.0       0.00      0.00      0.00       1.0
       245.0       0.00      0.00      0.00       1.0
       249.0       0.00      0.00      0.00       1.0
       253.0       0.00      0.00      0.00       1.0
       255.0       0.00      0.00      0.00       1.0
       258.0       0.00      0.00      0.00       0.0
       259.0       0.00      0.00      0.00       2.0
       260.0       0.00      0.00      0.00       1.0
       262.0       0.00      0.00      0.00       1.0
       264.0       0.00      0.00      0.00       0.0
       265.0       0.00      0.00      0.00       1.0
       266.0       0.00      0.00      0.00       0.0
       267.0       0.00      0.00      0.00       1.0
       268.0       0.00      0.00      0.00       1.0
       270.0       0.00      0.00      0.00       1.0
       274.0       0.00      0.00      0.00       1.0
       275.0       0.00      0.00      0.00       0.0
       277.0       0.00      0.00      0.00       1.0
       280.0       0.00      0.00      0.00       1.0
       281.0       0.00      0.00      0.00       1.0
       287.0       0.00      0.00      0.00       0.0
       291.0       0.00      0.00      0.00       1.0
       292.0       0.00      0.00      0.00       0.0
       293.0       0.00      0.00      0.00       1.0
       299.0       0.00      0.00      0.00       1.0
       302.0       0.00      0.00      0.00       1.0
       303.0       0.00      0.00      0.00       0.0
       304.0       0.00      0.00      0.00       0.0
       309.0       0.00      0.00      0.00       1.0
       312.0       0.00      0.00      0.00       1.0
       318.0       0.00      0.00      0.00       1.0
       334.0       0.00      0.00      0.00       1.0
       337.0       0.00      0.00      0.00       1.0
       341.0       0.00      0.00      0.00       0.0
       343.0       0.00      0.00      0.00       1.0
       344.0       0.00      0.00      0.00       0.0
       352.0       0.00      0.00      0.00       1.0
       361.0       0.00      0.00      0.00       0.0
       362.0       0.00      0.00      0.00       1.0
       363.0       0.00      0.00      0.00       0.0
       370.0       0.00      0.00      0.00       1.0
       372.0       0.00      0.00      0.00       0.0
       373.0       0.00      0.00      0.00       1.0
       380.0       0.00      0.00      0.00       0.0
       385.0       0.00      0.00      0.00       1.0
       386.0       0.00      0.00      0.00       1.0
       389.0       0.00      0.00      0.00       1.0
       392.0       0.00      0.00      0.00       1.0
       400.0       0.00      0.00      0.00       0.0
       414.0       0.00      0.00      0.00       1.0
       415.0       0.00      0.00      0.00       1.0
       420.0       0.00      0.00      0.00       0.0
       426.0       0.00      0.00      0.00       1.0
       428.0       0.00      0.00      0.00       0.0
       429.0       0.00      0.00      0.00       2.0
       444.0       0.00      0.00      0.00       1.0
       446.0       0.00      0.00      0.00       1.0
       450.0       0.00      0.00      0.00       0.0
       451.0       0.00      0.00      0.00       0.0
       454.0       0.00      0.00      0.00       0.0
       457.0       0.00      0.00      0.00       1.0
       458.0       0.00      0.00      0.00       1.0
       461.0       0.00      0.00      0.00       1.0
       462.0       0.00      0.00      0.00       0.0
       463.0       0.00      0.00      0.00       1.0
       466.0       0.00      0.00      0.00       1.0
       469.0       0.00      0.00      0.00       1.0
       473.0       0.00      0.00      0.00       1.0
       475.0       0.00      0.00      0.00       1.0
       476.0       0.00      0.00      0.00       0.0
       480.0       0.00      0.00      0.00       1.0
       486.0       0.00      0.00      0.00       1.0
       487.0       0.00      0.00      0.00       0.0
       491.0       0.00      0.00      0.00       1.0
       495.0       0.00      0.00      0.00       1.0
       505.0       0.00      0.00      0.00       0.0
       515.0       0.00      0.00      0.00       0.0
       529.0       0.00      0.00      0.00       1.0
       535.0       0.00      0.00      0.00       0.0
       536.0       0.00      0.00      0.00       1.0
       541.0       0.00      0.00      0.00       0.0
       546.0       0.00      0.00      0.00       1.0
       547.0       0.00      0.00      0.00       1.0
       552.0       0.00      0.00      0.00       1.0
       556.0       0.00      0.00      0.00       0.0
       563.0       0.00      0.00      0.00       1.0
       574.0       0.00      0.00      0.00       1.0
       586.0       0.00      0.00      0.00       2.0
       587.0       0.00      0.00      0.00       0.0
       591.0       0.00      0.00      0.00       1.0
       602.0       0.00      0.00      0.00       0.0
       607.0       0.00      0.00      0.00       1.0
       608.0       0.00      0.00      0.00       1.0
       617.0       0.00      0.00      0.00       0.0
       618.0       0.00      0.00      0.00       1.0
       628.0       0.00      0.00      0.00       1.0
       639.0       0.00      0.00      0.00       0.0
       643.0       0.00      0.00      0.00       1.0
       648.0       0.00      0.00      0.00       1.0
       658.0       0.00      0.00      0.00       0.0
       664.0       0.00      0.00      0.00       0.0
       666.0       0.00      0.00      0.00       0.0
       669.0       0.00      0.00      0.00       1.0
       670.0       0.00      0.00      0.00       1.0
       681.0       0.00      0.00      0.00       0.0
       705.0       0.00      0.00      0.00       1.0
       714.0       0.00      0.00      0.00       1.0
       724.0       0.00      0.00      0.00       1.0
       748.0       0.00      0.00      0.00       1.0
       760.0       0.00      0.00      0.00       0.0
       763.0       0.00      0.00      0.00       0.0
       775.0       0.00      0.00      0.00       0.0
       777.0       0.00      0.00      0.00       0.0
       782.0       0.00      0.00      0.00       1.0
       798.0       0.00      0.00      0.00       0.0
       801.0       0.00      0.00      0.00       0.0
       804.0       0.00      0.00      0.00       0.0
       809.0       0.00      0.00      0.00       1.0
       830.0       0.00      0.00      0.00       2.0
       835.0       0.00      0.00      0.00       1.0
       862.0       0.00      0.00      0.00       1.0
       863.0       0.00      0.00      0.00       1.0
       870.0       0.00      0.00      0.00       0.0
       904.0       0.00      0.00      0.00       0.0
       906.0       0.00      0.00      0.00       0.0
       942.0       0.00      0.00      0.00       0.0
       981.0       0.00      0.00      0.00       0.0
       988.0       0.00      0.00      0.00       2.0
      1005.0       0.00      0.00      0.00       0.0
      1037.0       0.00      0.00      0.00       1.0
      1048.0       0.00      0.00      0.00       1.0
      1053.0       0.00      0.00      0.00       1.0
      1098.0       0.00      0.00      0.00       1.0
      1129.0       0.00      0.00      0.00       0.0
      1193.0       0.00      0.00      0.00       0.0
      1453.0       0.00      0.00      0.00       1.0
      1612.0       0.00      0.00      0.00       0.0
      1626.0       0.00      0.00      0.00       1.0
      1686.0       0.00      0.00      0.00       1.0
      1724.0       0.00      0.00      0.00       0.0
      1766.0       0.00      0.00      0.00       1.0
      1895.0       0.00      0.00      0.00       0.0
      1904.0       0.00      0.00      0.00       1.0
      2104.0       0.00      0.00      0.00       0.0
      2457.0       0.00      0.00      0.00       1.0
      2766.0       0.00      0.00      0.00       1.0
      2805.0       0.00      0.00      0.00       1.0
      2846.0       0.00      0.00      0.00       0.0
      2858.0       0.00      0.00      0.00       1.0
      2878.0       0.00      0.00      0.00       0.0
      2906.0       0.00      0.00      0.00       0.0
      2974.0       0.00      0.00      0.00       0.0
      3101.0       0.00      0.00      0.00       0.0
      3284.0       0.00      0.00      0.00       1.0
      3400.0       0.00      0.00      0.00       0.0
      3887.0       0.00      0.00      0.00       1.0
      5480.0       0.00      0.00      0.00       1.0
      5520.0       0.00      0.00      0.00       0.0
      5521.0       0.00      0.00      0.00       1.0
      5933.0       0.00      0.00      0.00       1.0
      6051.0       0.00      0.00      0.00       1.0
      6059.0       0.00      0.00      0.00       0.0
      6144.0       0.00      0.00      0.00       0.0
      6190.0       0.00      0.00      0.00       0.0
      6301.0       0.00      0.00      0.00       1.0

    accuracy                           0.00     153.0
   macro avg       0.00      0.00      0.00     153.0
weighted avg       0.00      0.00      0.00     153.0

C:\Users\EJ-PC\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\EJ-PC\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\EJ-PC\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\EJ-PC\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\EJ-PC\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\EJ-PC\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))