In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np 
import tensorflow as tf
from sklearn.metrics import classification_report
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, root_mean_squared_error
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import load_model
import joblib

In [2]:
# Import our input dataset
crime_df = pd.read_csv('All_data_cleaned.csv')
crime_df.head()

# One-hot encode the 'City' column
crime_encoded = pd.get_dummies(crime_df, columns=['City'])

# Initialize the LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the 'City' column
crime_df['City_encoded'] = label_encoder.fit_transform(crime_df['City'])

crime_df

,Year,City,Population 25 years and over - Less than 9th grade,Percent Population 25 years and over - Less than 9th grade,Population 25 years and over - 9th to12th (No Diploma),Percent Population 25 years and over - 9th to12th (No Diploma),Population 25 years and over - High School Graduate (and equivalent),Percent Population 25 years and over - High School Graduate (and equivalent),"Population 25 years and over - Some college, no degree","Percent Population 25 years and over - Some college, no degree",...,Percent Home Occupied,Percent Renter Occupied,Percent 25+,Percent 14-,Percent 15 to 24,Percent Uneducated,Percent Higher Education,Sum Uneducated,Sum Higher Education,City_encoded
0,2010,Alameda,2752,5.50,2234,4.50,8546,17.00,10009,19.90,...,46.920853,53.079147,65.8,19.8,12.3,10.00,53.10,4986,26639,0
1,2010,Alhambra,6236,10.10,4575,7.40,13358,21.70,12091,19.60,...,38.053381,61.946619,71.1,12.9,13.1,17.50,41.10,10811,25307,1
2,2010,Anaheim,32561,15.50,22329,10.70,50982,24.30,39407,18.80,...,48.388510,51.611490,61.0,21.2,16.7,26.20,30.70,54890,64362,2
3,2010,Antioch,4874,7.70,4633,7.30,17092,26.90,20113,31.70,...,62.767194,37.232806,60.7,22.9,15.5,15.00,26.50,9507,16815,3
4,2010,Apple Valley,639,1.50,3353,7.70,14524,33.40,11690,26.90,...,70.690377,29.309623,60.4,23.4,13.9,9.20,30.50,3992,13303,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,2019,Vista,10080,15.05,6638,9.91,13245,19.77,16027,23.93,...,45.724859,54.275141,64.4,19.9,14.1,24.96,31.34,16718,20990,129
1161,2019,West Covina,5308,7.09,4530,6.05,20919,27.95,16083,21.49,...,57.975360,42.024640,69.5,16.9,11.9,13.14,37.41,9838,28003,131
1162,2019,Westminster,8307,13.03,6607,10.36,15641,24.53,11273,17.68,...,47.216869,52.783131,68.0,18.2,11.5,23.39,34.41,14914,21943,132
1163,2019,Whittier,3021,5.44,3921,7.06,16232,29.24,12079,21.76,...,60.928433,39.071567,63.3,21.0,13.9,12.50,36.49,6942,20258,133
1164,2019,Yuba City,5344,11.93,4756,10.62,9396,20.97,11112,24.80,...,54.540237,45.459763,64.6,18.2,15.0,22.55,31.69,10100,14192,135

,Year,City,Population 25 years and over - Less than 9th grade,Percent Population 25 years and over - Less than 9th grade,Population 25 years and over - 9th to12th (No Diploma),Percent Population 25 years and over - 9th to12th (No Diploma),Population 25 years and over - High School Graduate (and equivalent),Percent Population 25 years and over - High School Graduate (and equivalent),"Population 25 years and over - Some college, no degree","Percent Population 25 years and over - Some college, no degree",...,Percent Home Occupied,Percent Renter Occupied,Percent 25+,Percent 14-,Percent 15 to 24,Percent Uneducated,Percent Higher Education,Sum Uneducated,Sum Higher Education,City_encoded
0,2010,Alameda,2752,5.50,2234,4.50,8546,17.00,10009,19.90,...,46.920853,53.079147,65.8,19.8,12.3,10.00,53.10,4986,26639,0
1,2010,Alhambra,6236,10.10,4575,7.40,13358,21.70,12091,19.60,...,38.053381,61.946619,71.1,12.9,13.1,17.50,41.10,10811,25307,1
2,2010,Anaheim,32561,15.50,22329,10.70,50982,24.30,39407,18.80,...,48.388510,51.611490,61.0,21.2,16.7,26.20,30.70,54890,64362,2
3,2010,Antioch,4874,7.70,4633,7.30,17092,26.90,20113,31.70,...,62.767194,37.232806,60.7,22.9,15.5,15.00,26.50,9507,16815,3
4,2010,Apple Valley,639,1.50,3353,7.70,14524,33.40,11690,26.90,...,70.690377,29.309623,60.4,23.4,13.9,9.20,30.50,3992,13303,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,2019,Vista,10080,15.05,6638,9.91,13245,19.77,16027,23.93,...,45.724859,54.275141,64.4,19.9,14.1,24.96,31.34,16718,20990,129
1161,2019,West Covina,5308,7.09,4530,6.05,20919,27.95,16083,21.49,...,57.975360,42.024640,69.5,16.9,11.9,13.14,37.41,9838,28003,131
1162,2019,Westminster,8307,13.03,6607,10.36,15641,24.53,11273,17.68,...,47.216869,52.783131,68.0,18.2,11.5,23.39,34.41,14914,21943,132
1163,2019,Whittier,3021,5.44,3921,7.06,16232,29.24,12079,21.76,...,60.928433,39.071567,63.3,21.0,13.9,12.50,36.49,6942,20258,133
1164,2019,Yuba City,5344,11.93,4756,10.62,9396,20.97,11112,24.80,...,54.540237,45.459763,64.6,18.2,15.0,22.55,31.69,10100,14192,135

In [3]:
# Fix the seed for random number generation
seed_value = 8
np.random.seed(seed_value)
tf.random.set_seed(seed_value)

# Remove crime and city target from features data
X = crime_df.copy()
X.drop(columns=["Crime_Rate_per_100k", 
                "City",
                "Violent Crimes Sum",
                "City_encoded",
                "Year"
               ], axis=1, inplace=True)
y = crime_df['Crime_Rate_per_100k']

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 3: Split Data
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.1, random_state=8)

In [4]:
# X.to_csv('input2.csv', index=False)

In [5]:
model_path = 'NN-final.keras'
model = load_model(model_path)

In [6]:
#predict
predictions = model.predict(X_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

In [7]:
if predictions.ndim != 1:
    predictions = predictions.flatten()

# Check if 'y_test' is not 1-dimensional and reshape if necessary
if y_test.ndim != 1:
    x = y_test.flatten()

In [8]:
mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
rmse = root_mean_squared_error(y_test, predictions)  # Updated line
r2 = r2_score(y_test, predictions)

print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R²): {r2}")

errors = abs(predictions - y_test)
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_test)

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Mean Absolute Error (MAE): 73.7017664496407
Mean Squared Error (MSE): 11250.689180819843
Root Mean Squared Error (RMSE): 106.06926595776858
R-squared (R²): 0.8008324593269722
Accuracy: 75.55 %.
Mean Absolute Error (MAE): 73.7017664496407
Mean Squared Error (MSE): 11250.689180819843
Root Mean Squared Error (RMSE): 106.06926595776858
R-squared (R²): 0.8008324593269722
Accuracy: 75.55 %.

In [9]:
# Load the model from the file
model2 = joblib.load('random_forest_regressor.pkl')

In [10]:
predictions2 = model2.predict(X_test)

In [11]:
mae = mean_absolute_error(y_test, predictions2)
mse = mean_squared_error(y_test, predictions2)
rmse = root_mean_squared_error(y_test, predictions2)  # Updated line
r2 = r2_score(y_test, predictions2)

print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R²): {r2}")

errors = abs(predictions2 - y_test)
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_test)

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Mean Absolute Error (MAE): 86.56685218494285
Mean Squared Error (MSE): 15928.467648757092
Root Mean Squared Error (RMSE): 126.20803321800516
R-squared (R²): 0.7180231648652071
Accuracy: 68.81 %.
Mean Absolute Error (MAE): 86.56685218494285
Mean Squared Error (MSE): 15928.467648757092
Root Mean Squared Error (RMSE): 126.20803321800516
R-squared (R²): 0.7180231648652071
Accuracy: 68.81 %.

In [12]:
model3 = joblib.load('linear_regression_model.pkl')

In [13]:
predictions3 = model3.predict(X_test)

In [14]:
mae = mean_absolute_error(y_test, predictions3)
mse = mean_squared_error(y_test, predictions3)
rmse = root_mean_squared_error(y_test, predictions3)  # Updated line
r2 = r2_score(y_test, predictions3)

print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R²): {r2}")

errors = abs(predictions3 - y_test)
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_test)

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Mean Absolute Error (MAE): 411039657049.28424
Mean Squared Error (MSE): 5.5243341472272505e+23
Root Mean Squared Error (RMSE): 743258645911.8556
R-squared (R²): -9.779561307542075e+18
Accuracy: -149806060789.37 %.
Mean Absolute Error (MAE): 411039657049.28424
Mean Squared Error (MSE): 5.5243341472272505e+23
Root Mean Squared Error (RMSE): 743258645911.8556
R-squared (R²): -9.779561307542075e+18
Accuracy: -149806060789.37 %.