In [2]:
import pandas as pd

In [14]:
# read file
file_path = 'Age_2015.csv'

df = pd.read_csv(file_path)

print(df)

               Label (Grouping) SEX AND AGE!!Total population  \
0                    California                           NaN
1                      Estimate                    39,144,818
2                       Percent                    39,144,818
3      Alameda city, California                           NaN
4                      Estimate                        78,614
..                          ...                           ...
409                    Estimate                        67,966
410                     Percent                        67,966
411  Yuba City city, California                           NaN
412                    Estimate                        66,944
413                     Percent                        66,944

    SEX AND AGE!!Under 5 years SEX AND AGE!!5 to 9 years  \
0                          NaN                       NaN
1                    2,507,649                 2,540,713
2                        6.40%                     6.50%
3                          NaN                       NaN
4                        4,187                     4,856
..                         ...                       ...
409                      2,845                     4,031
410                      4.20%                     5.90%
411                        NaN                       NaN
412                      4,693                     5,485
413                      7.00%                     8.20%

    SEX AND AGE!!10 to 14 years SEX AND AGE!!15 to 19 years  \
0                           NaN                         NaN
1                     2,519,716                   2,606,760
2                         6.40%                       6.70%
3                           NaN                         NaN
4                         4,035                       2,754
..                          ...                         ...
409                       4,375                       5,319
410                       6.40%                       7.80%
411                         NaN                         NaN
412                       4,591                       4,469
413                       6.90%                       6.70%

    SEX AND AGE!!20 to 24 years SEX AND AGE!!25 to 34 years  \
0                           NaN                         NaN
1                     2,884,717                   5,832,712
2                         7.40%                      14.90%
3                           NaN                         NaN
4                         4,002                      11,336
..                          ...                         ...
409                       3,615                       5,944
410                       5.30%                       8.70%
411                         NaN                         NaN
412                       4,733                      10,048
413                       7.10%                      15.00%

    SEX AND AGE!!35 to 44 years SEX AND AGE!!45 to 54 years  ...  \
0                           NaN                         NaN  ...
1                     5,190,370                   5,243,141  ...
2                        13.30%                      13.40%  ...
3                           NaN                         NaN  ...
4                        12,386                      12,602  ...
..                          ...                         ...  ...
409                       7,252                      10,367  ...
410                      10.70%                      15.30%  ...
411                         NaN                         NaN  ...
412                       7,823                       8,698  ...
413                      11.70%                      13.00%  ...

    SEX AND AGE!!60 to 64 years SEX AND AGE!!65 to 74 years  \
0                           NaN                         NaN
1                     2,149,326                   2,981,899
2                         5.50%                       7.60%
3                           NaN                         NaN
4                         5,014                       6,529
..                          ...                         ...
409                       6,182                       7,153
410                       9.10%                      10.50%
411                         NaN                         NaN
412                       2,874                       6,635
413                       4.30%                       9.90%

    SEX AND AGE!!75 to 84 years SEX AND AGE!!85 years and over  \
0                           NaN                            NaN
1                     1,518,127                        689,532
2                         3.90%                          1.80%
3                           NaN                            NaN
4                         3,599                          1,541
..                          ...                            ...
409                       2,672                          1,411
410                       3.90%                          2.10%
411                         NaN                            NaN
412                       2,201                          1,326
413                       3.30%                          2.00%

    SEX AND AGE!!18 years and over SEX AND AGE!!21 years and over  \
0                              NaN                            NaN
1                       30,028,400                     28,389,782
2                           76.70%                         72.50%
3                              NaN                            NaN
4                           63,622                         62,228
..                             ...                            ...
409                         52,598                         50,839
410                         77.40%                         74.80%
411                            NaN                            NaN
412                         48,608                         47,361
413                         72.60%                         70.70%

    SEX AND AGE!!62 years and over SEX AND AGE!!65 years and over  \
0                              NaN                            NaN
1                        6,417,044                      5,189,558
2                           16.40%                         13.30%
3                              NaN                            NaN
4                           14,311                         11,669
..                             ...                            ...
409                         14,382                         11,236
410                         21.20%                         16.50%
411                            NaN                            NaN
412                         11,979                         10,162
413                         17.90%                         15.20%

    SEX AND AGE!!18 years and over.1 SEX AND AGE!!65 years and over.1
0                                NaN                              NaN
1                         30,028,400                        5,189,558
2                         30,028,400                        5,189,558
3                                NaN                              NaN
4                             63,622                           11,669
..                               ...                              ...
409                           52,598                           11,236
410                           52,598                           11,236
411                              NaN                              NaN
412                           48,608                           10,162
413                           48,608                           10,162

[414 rows x 21 columns]

In [9]:
# remoove the unwanted rows
df = df[~df['Label (Grouping)'].str.contains('Margin of Error|Percent Margin of Error', case=False)]

print(df)

               Label (Grouping) SEX AND AGE!!Total population  \
0                    California                           NaN
1                      Estimate                    39,144,818
2                       Percent                    39,144,818
3      Alameda city, California                           NaN
4                      Estimate                        78,614
..                          ...                           ...
669                    Estimate                        67,966
671                     Percent                        67,966
673  Yuba City city, California                           NaN
674                    Estimate                        66,944
676                     Percent                        66,944

    SEX AND AGE!!Under 5 years SEX AND AGE!!5 to 9 years  \
0                          NaN                       NaN
1                    2,507,649                 2,540,713
2                        6.40%                     6.50%
3                          NaN                       NaN
4                        4,187                     4,856
..                         ...                       ...
669                      2,845                     4,031
671                      4.20%                     5.90%
673                        NaN                       NaN
674                      4,693                     5,485
676                      7.00%                     8.20%

    SEX AND AGE!!10 to 14 years SEX AND AGE!!15 to 19 years  \
0                           NaN                         NaN
1                     2,519,716                   2,606,760
2                         6.40%                       6.70%
3                           NaN                         NaN
4                         4,035                       2,754
..                          ...                         ...
669                       4,375                       5,319
671                       6.40%                       7.80%
673                         NaN                         NaN
674                       4,591                       4,469
676                       6.90%                       6.70%

    SEX AND AGE!!20 to 24 years SEX AND AGE!!25 to 34 years  \
0                           NaN                         NaN
1                     2,884,717                   5,832,712
2                         7.40%                      14.90%
3                           NaN                         NaN
4                         4,002                      11,336
..                          ...                         ...
669                       3,615                       5,944
671                       5.30%                       8.70%
673                         NaN                         NaN
674                       4,733                      10,048
676                       7.10%                      15.00%

    SEX AND AGE!!35 to 44 years SEX AND AGE!!45 to 54 years  ...  \
0                           NaN                         NaN  ...
1                     5,190,370                   5,243,141  ...
2                        13.30%                      13.40%  ...
3                           NaN                         NaN  ...
4                        12,386                      12,602  ...
..                          ...                         ...  ...
669                       7,252                      10,367  ...
671                      10.70%                      15.30%  ...
673                         NaN                         NaN  ...
674                       7,823                       8,698  ...
676                      11.70%                      13.00%  ...

    SEX AND AGE!!60 to 64 years SEX AND AGE!!65 to 74 years  \
0                           NaN                         NaN
1                     2,149,326                   2,981,899
2                         5.50%                       7.60%
3                           NaN                         NaN
4                         5,014                       6,529
..                          ...                         ...
669                       6,182                       7,153
671                       9.10%                      10.50%
673                         NaN                         NaN
674                       2,874                       6,635
676                       4.30%                       9.90%

    SEX AND AGE!!75 to 84 years SEX AND AGE!!85 years and over  \
0                           NaN                            NaN
1                     1,518,127                        689,532
2                         3.90%                          1.80%
3                           NaN                            NaN
4                         3,599                          1,541
..                          ...                            ...
669                       2,672                          1,411
671                       3.90%                          2.10%
673                         NaN                            NaN
674                       2,201                          1,326
676                       3.30%                          2.00%

    SEX AND AGE!!18 years and over SEX AND AGE!!21 years and over  \
0                              NaN                            NaN
1                       30,028,400                     28,389,782
2                           76.70%                         72.50%
3                              NaN                            NaN
4                           63,622                         62,228
..                             ...                            ...
669                         52,598                         50,839
671                         77.40%                         74.80%
673                            NaN                            NaN
674                         48,608                         47,361
676                         72.60%                         70.70%

    SEX AND AGE!!62 years and over SEX AND AGE!!65 years and over  \
0                              NaN                            NaN
1                        6,417,044                      5,189,558
2                           16.40%                         13.30%
3                              NaN                            NaN
4                           14,311                         11,669
..                             ...                            ...
669                         14,382                         11,236
671                         21.20%                         16.50%
673                            NaN                            NaN
674                         11,979                         10,162
676                         17.90%                         15.20%

    SEX AND AGE!!18 years and over.1 SEX AND AGE!!65 years and over.1
0                                NaN                              NaN
1                         30,028,400                        5,189,558
2                         30,028,400                        5,189,558
3                                NaN                              NaN
4                             63,622                           11,669
..                               ...                              ...
669                           52,598                           11,236
671                           52,598                           11,236
673                              NaN                              NaN
674                           48,608                           10,162
676                           48,608                           10,162

[414 rows x 21 columns]

In [13]:
# save the changes to the csv file
df.to_csv('Age_2015.csv', index=False)
print('changes saved')

changes saved