In [11]:
import pandas as pd
from pathlib import Path

poverty_2010 = pd.read_csv("Education_level_yearly_data/Ed_2010.csv")
poverty_2011 = pd.read_csv("Education_level_yearly_data/Ed_2011.csv")
poverty_2012 = pd.read_csv("Education_level_yearly_data/Ed_2012.csv")
poverty_2013 = pd.read_csv("Education_level_yearly_data/Ed_2013.csv")
poverty_2014 = pd.read_csv("Education_level_yearly_data/Ed_2014.csv")

poverty_2010

,GEO_ID,NAME,DP02_0001E,DP02_0001M,DP02_0001PE,DP02_0001PM,DP02_0002E,DP02_0002M,DP02_0002PE,DP02_0002PM,...,DP02_0147PM,DP02_0148E,DP02_0148M,DP02_0148PE,DP02_0148PM,DP02_0149E,DP02_0149M,DP02_0149PE,DP02_0149PM,Unnamed: 598
0,Geography,Geographic Area Name,Estimate!!HOUSEHOLDS BY TYPE!!Total households,Estimate Margin of Error!!HOUSEHOLDS BY TYPE!!...,Percent!!HOUSEHOLDS BY TYPE!!Total households,Percent Margin of Error!!HOUSEHOLDS BY TYPE!!T...,Estimate!!HOUSEHOLDS BY TYPE!!Family household...,Estimate Margin of Error!!HOUSEHOLDS BY TYPE!!...,Percent!!HOUSEHOLDS BY TYPE!!Family households...,Percent Margin of Error!!HOUSEHOLDS BY TYPE!!F...,...,Percent Margin of Error!!ANCESTRY!!Ukrainian,Estimate!!ANCESTRY!!Welsh,Estimate Margin of Error!!ANCESTRY!!Welsh,Percent!!ANCESTRY!!Welsh,Percent Margin of Error!!ANCESTRY!!Welsh,Estimate!!ANCESTRY!!West Indian (excluding His...,Estimate Margin of Error!!ANCESTRY!!West India...,Percent!!ANCESTRY!!West Indian (excluding Hisp...,Percent Margin of Error!!ANCESTRY!!West Indian...,NaN
1,1600000US0600562,"Alameda city, California",28011,1368,28011,(X),18236,1066,65.1,4.0,...,0.3,169,218,0.2,0.3,207,249,0.3,0.3,NaN
2,1600000US0600884,"Alhambra city, California",28100,2034,28100,(X),19964,1300,71.0,4.6,...,N,N,N,N,N,N,N,N,N,NaN
3,1600000US0602000,"Anaheim city, California",100404,3112,100404,(X),75396,2109,75.1,2.3,...,0.1,670,323,0.2,0.1,0,294,0.0,0.1,NaN
4,1600000US0602252,"Antioch city, California",30970,2008,30970,(X),24708,1655,79.8,3.3,...,0.2,432,303,0.4,0.3,730,805,0.7,0.8,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,1600000US0682996,"Vista city, California",29982,1899,29982,(X),20656,1320,68.9,4.3,...,0.2,376,269,0.4,0.3,60,101,0.1,0.1,NaN
124,1600000US0684200,"West Covina city, California",31286,1738,31286,(X),25023,1305,80.0,3.2,...,0.2,131,151,0.1,0.1,266,313,0.3,0.3,NaN
125,1600000US0684550,"Westminster city, California",26838,1402,26838,(X),20591,1043,76.7,3.9,...,0.3,156,147,0.2,0.2,0,294,0.0,0.2,NaN
126,1600000US0685292,"Whittier city, California",27969,1935,27969,(X),19738,1152,70.6,4.5,...,0.2,334,299,0.4,0.3,45,76,0.1,0.1,NaN
127,1600000US0686832,"Yorba Linda city, California",21292,1090,21292,(X),17178,763,80.7,3.8,...,0.1,429,395,0.7,0.6,56,93,0.1,0.1,NaN

In [12]:
df = [
    (poverty_2010, "2010"),
    (poverty_2011, "2011"),
    (poverty_2012, "2012"),
    (poverty_2013, "2013"),
    (poverty_2014, "2014")]

In [13]:
def clean(df):
    clean_df = []
    for dataframe, year in df:
            dataframe = dataframe.drop(columns=[column for column in dataframe.columns if column.endswith('M')])
            dataframe = dataframe.drop(columns=["GEO_ID"])
            dataframe = dataframe.drop(columns=dataframe.columns[dataframe.apply(lambda col: col.astype(str).str.contains('\(X\)').any())])
            dataframe["NAME"] = dataframe["NAME"].str.replace(', California|city|CDP|town', '', regex=True)
            dataframe["NAME"] = dataframe["NAME"].str.strip()
            dataframe["Year"] = year   
            dataframe = dataframe[["Year", "NAME", "DP02_0059E", "DP02_0059PE", "DP02_0060E",
                                   "DP02_0060PE", "DP02_0061E", "DP02_0061PE", "DP02_0062E",
                                   "DP02_0062PE", "DP02_0063E", "DP02_0063PE", "DP02_0064E",
                                   "DP02_0064PE", "DP02_0065E", "DP02_0065PE"]]
            dataframe = dataframe.rename(columns={
                "NAME": "City",
                "DP02_0059E": "Population 25 years and over - Less than 9th grade",
                "DP02_0059PE": "Percent Population 25 years and over - Less than 9th grade",
                "DP02_0060E": "Population 25 years and over - 9th to 12th (No Diploma)",
                "DP02_0060PE": "Percent Population 25 years and over - 9th to 12th (No Diploma)",
                "DP02_0061E": "Population 25 years and over - High School Graduate (and equivalent)",
                "DP02_0061PE": "Percent Population 25 years and over - High School Graduate (and equivalent)",
                "DP02_0062E": "Population 25 years and over - Some college, no degree",
                "DP02_0062PE": "Percent Population 25 years and over - Some college, no degree",
                "DP02_0063E": "Population 25 years and over - Associate's degree",
                "DP02_0063PE": "Percent Population 25 years and over - Associate's degree",
                "DP02_0064E": "Population 25 years and over - Bachelor's degree",
                "DP02_0064PE": "Percent Population 25 years and over - Bachelor's degree",
                "DP02_0065E": "Population 25 years and over - Graduate or Prefessional Degree",
                "DP02_0065PE": "Percent Population 25 years and over - Graduate or Prefessional Degree"})
            dataframe = dataframe.drop(dataframe.index[0])
            clean_df.append(dataframe)
    return clean_df
cleaned_df = clean(df)

In [14]:
cleaned_df[0]

,Year,City,Population 25 years and over - Less than 9th grade,Percent Population 25 years and over - Less than 9th grade,Population 25 years and over - 9th to 12th (No Diploma),Percent Population 25 years and over - 9th to 12th (No Diploma),Population 25 years and over - High School Graduate (and equivalent),Percent Population 25 years and over - High School Graduate (and equivalent),"Population 25 years and over - Some college, no degree","Percent Population 25 years and over - Some college, no degree",Population 25 years and over - Associate's degree,Percent Population 25 years and over - Associate's degree,Population 25 years and over - Bachelor's degree,Percent Population 25 years and over - Bachelor's degree,Population 25 years and over - Graduate or Prefessional Degree,Percent Population 25 years and over - Graduate or Prefessional Degree
1,2010,Alameda,2752,5.5,2234,4.5,8546,17.0,10009,19.9,2894,5.8,15544,31.0,8201,16.3
2,2010,Alhambra,6236,10.1,4575,7.4,13358,21.7,12091,19.6,5497,8.9,13368,21.7,6442,10.5
3,2010,Anaheim,32561,15.5,22329,10.7,50982,24.3,39407,18.8,14130,6.7,37672,18.0,12560,6.0
4,2010,Antioch,4874,7.7,4633,7.3,17092,26.9,20113,31.7,5569,8.8,8629,13.6,2617,4.1
5,2010,Apple Valley,639,1.5,3353,7.7,14524,33.4,11690,26.9,4802,11.0,4582,10.5,3919,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,2010,Vista,9858,16.9,5889,10.1,12355,21.2,13224,22.7,5051,8.7,8638,14.8,3182,5.5
124,2010,West Covina,6105,9.2,6607,10.0,15584,23.5,15897,24.0,5109,7.7,11551,17.4,5416,8.2
125,2010,Westminster,8597,14.3,7745,12.9,14951,24.9,12868,21.4,4671,7.8,8681,14.5,2562,4.3
126,2010,Whittier,3635,6.5,6249,11.2,13085,23.5,15352,27.5,5264,9.4,7702,13.8,4509,8.1
127,2010,Yorba Linda,1562,3.6,1054,2.5,6248,14.6,11338,26.5,4089,9.5,11953,27.9,6602,15.4

In [15]:
years = ["2010", "2011", "2012", "2013", "2014"]
file_name = {f"Cleaned_Ed_{year}": df for df, year in zip(cleaned_df, years)}
for name, df in file_name.items():
    csv_path= f"{name}.csv"
    df.to_csv(csv_path, index=False)